# Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению. 
# Некоторые шаблоны требуют предварительной настройки перед запуском.
#
# Подробнее о синтаксисе можно узнать в документации:
# https://docs.gitflic.ru/cicd/gitflic-ci-yaml

image: ubuntu:latest

before_script:
  - echo "Подготовка к CI/CD"
  - sudo apt update -y
  - sudo apt install openjdk-17-jdk
  - wget -O junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar
  - mkdir bin

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Запуск сборки"
    - javac -d bin core\ServerThread.java
    - javac -d bin -cp bin;junit.jar core/ServerThreadTest.java
    - javac -d bin Main.java 

test:
  stage: test
  script:
    - echo "Запуск тестов"
    - java -jar junit.jar -cp bin --select-class core.ServerThreadTest > test.result
  needs:
    - build
  artifacts:
    paths: 
      - test.result
#deploy:
#  stage: deploy
#  script:
#    - echo $(cat build.txt)
#    - echo "Развертывание проекта"
#  needs:
#    - build
#  rules:
#    - if: $TEST_1_SUCCESS == "true" && $TEST_2_SUCCESS == "true"
  
#after_script:
#  - echo "Скрипт после основных инструкций (в каждой задаче)"
