# Учебный скрипт для GiHub
name: SimpleServer CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build_test:
    name: Build classes for JUnit
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Build test!"
  build_main:
    name: Build main application
    needs: build_test
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Build main!"
  test:
    name: Test with JUnit
    needs: build_test
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Run test!"
  deploy:
    name: Deploy App
    needs: [build_main, test]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Run deploy!"
