# Учебный скрипт для GiHub
name: SimpleServer CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build classes for JUnit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare toolchain and environment
        run: |
          sudo apt update 2>/dev/null
          sudo apt install -y openjdk-17-jdk 2>/dev/null
          mkdir bin
          wget -O junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar 2>/dev/null
      - name: Compile ServerThread
        run: javac -d bin core/ServerThread.java
      - name: Compile JUnit tests
        run: javac -d bin -cp bin:./junit.jar core/ServerThreadTest.java
      - name: Compile Main
        run: javac -d bin Main.java
      - name: Save JUnit
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.jar
      - name: Save builds
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: bin
  test_linux:
    name: Test with JUnit on Linux
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare toolchain and environment
        run: |
          sudo apt update 2>/dev/null
          sudo apt install -y openjdk-17-jdk 2>/dev/null
      - name: Restore JUnit
        uses: actions/download-artifact@v4
        with:
          name: junit
      - name: Restore builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Start JUnit tests
        run: java -jar junit.jar -cp ./ --select-class core.ServerThreadTest
  test_windows:
    name: Test with JUnit on Windows
    needs: build
    runs-on: windows-2022
    steps:
      - name: Install OpenJDK
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop bucket add java
          scoop install openjdk17
      - name: Restore JUnit
        uses: actions/download-artifact@v4
        with:
          name: junit
      - name: Restore builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Start JUnit tests
        shell: pwsh
        run: |
          java --version
          java -jar junit.jar -cp .\ --select-class core.ServerThreadTest
  deploy:
    name: Deploy App
    needs: [build, test_linux, test_windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Restore builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Try to stop server and delete old files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop simple_server.service
            sleep 2
            rm -rf app
            mkdir -p app/core
      - name: Try to copy App to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.class,core/*.class,!core/*Test.class"
          target: "/home/badlagger/app"
      - name: Try to run App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start simple_server.service
