# Учебный скрипт для GiHub
name: SimpleServer CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build classes for JUnit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare toolchain and environment
        run: |
          sudo apt update 2>/dev/null
          sudo apt install -y openjdk-17-jdk 2>/dev/null
          mkdir bin
          wget -O junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar 2>/dev/null
      - name: Compile ServerThread
        run: javac -d bin core/ServerThread.java
      - name: Compile JUnit tests
        run: javac -d bin -cp bin:./junit.jar core/ServerThreadTest.java
      - name: Compile Main
        run: javac -d bin Main.java
      - name: Save JUnit
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.jar
      - name: Save builds
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: bin
  test:
    name: Test with JUnit
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare toolchain and environment
        run: |
          sudo apt update 2>/dev/null
          sudo apt install -y openjdk-17-jdk 2>/dev/null
      - name: Restore JUnit
        uses: actions/download-artifact@v4
        with:
          name: junit
      - name: Restore builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Check restores
        run: ls -al
      - name: Start JUnit tests
        run: java -jar junit.jar -cp ./ --select-class core.ServerThreadTest
  deploy:
    name: Deploy App
    needs: [build, test]
    runs-on: ubuntu-22.04
    steps:
      - name: Restore builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Try to stop server and delete old files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 158.160.159.239
          username: badlagger
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch app/exit.state
            sleep 2
            rm -rf app
            mkdir -p app/core
      - name: Try to copy App to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 158.160.159.239
          username: badlagger
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.class,core/*.class,!core/*Test.class"
          target: "/home/badlagger/app"
