# Учебный скрипт для GiHub
name: SimpleServer CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build_test:
    name: Build classes for JUnit
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Build test!"
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          sudo mkdir bin
          ls -al
          javac -d bin core/ServerThread.java
          wget -O junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar
          javac -d bin -cp bin;junit.jar core/ServerThreadTest.java
          java -jar junit.jar -cp bin --select-class core.ServerThreadTest
  build_main:
    name: Build main application
    needs: build_test
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Build main!"
  test:
    name: Test with JUnit
    needs: build_test
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Run test!"
  deploy:
    name: Deploy App
    needs: [build_main, test]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Run deploy!"
